# Site settings
title: Mini-git punto de entrada
email: jjmerelo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pequeña referencia de `git` con comandos básicos y sitios donde empezar. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mini-git.github.io" # the base hostname & protocol for your site
twitter_username: jjmerelo
github_username:  JJ

# Build settings
markdown: kramdown

exclude: ["README.md"]
